### ISSUE TITLE
Babel selected but dependencies not installed

### ISSUE THREAD

**Issue by jshreyans** [sarthak-sehgal/wcg#2]
On initialising a project, Babel was selected but none of the dependencies show up in the package.json generated.

Here's the configuration I selected:
![Screenshot from 2019-07-24 19-18-40](https://user-images.githubusercontent.com/41480918/61798982-e76b7100-ae47-11e9-866e-112151b999e9.png)

**Comment by sarthak-sehgal** [comment]
Fixed in `v0.0.4`
Can you confirm and close the issue?

**Comment by jshreyans** [comment]
The problem seems to be resolved, but now I'm getting an EACCES error. Here's the output I got:
```sh
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/home/shreyans/.npm/_cacache/index-v5/c6/06/397b0995a61d738c73ec8b67a5d1ba1f6f23a9386f4c5590aa356a1a3120'
```
Although the Babel dependencies *were* being installed:
```sh
signal: null,
  cmd:
   'cd "/home/shreyans/Desktop/try-web" && npm init -y && npm i --save-dev webpack webpack-cli css-loader style-loader node-sass sass-loader url-loader html-loader babel-loader @babel/core @babel/preset-env && npm i --save ' }
```

It could be a problem with my local setup. If you want, I can attach the log file here

**Comment by sarthak-sehgal** [comment]
Can you retry after clearing npm cache (`npm cache clean`) and see if the error persists?

**Comment by jshreyans** [comment]
> Can you retry after clearing npm cache (npm cache clean) and see if the error persists?

I already tried that but the same error came up. I'll try to see if its a problem with my machine.

**Comment by jshreyans** [comment]
Seems to be an error with installing `@babel/preset-env` on my machine. I tried installing it in another project and it threw the same error. The other 2 dependencies work fine.

**Comment by sarthak-sehgal** [comment]
@jshreyans551 can I close this issue?
(closed below by mistake)

**Comment by jshreyans** [comment]
Yes it seems to be a temporary issue with the dependency. I think we can close this.
